### ISSUE TITLE
Real-time global MLST surveillance

### ISSUE THREAD

**Issue by sam-baird** [AllTheBacteria/AllTheBacteria#19]
Hello,

I'm happy to have stumbled across this project, it's very cool! I'm interested in contributing, and would like to apply this dataset for public health genomic surveillance

I have been interested in having near real-time, global MLST surveillance of all publicly available bacterial sequence data. I have a [toy attempt](https://github.com/sam-baird/mlst-seeker/tree/main) at doing something like this for a school project, but it's extremely limited (such as lack of QC, inefficient data access and typing, no centralized database, does not include samples with only raw reads). Ideally, I imagine the system having the following properties:

- Emphasize comprehensiveness over curation: include as much data as possible updated as frequently as possible
- Advanced searching capabilities: FASTQ ([stringMLST](https://github.com/jordanlab/stringMLST)?), FASTA, ST, locus variants, clonal complex, sample metadata filtering
- Warn about poor-quality sequences that may be problematic for downstream SNP / phylogenetic analysis, but still include them for comprehensive genomic surveillance
- Sync with PubMLST scheme definitions in "real-time" and update any existing records that have missing ST or allele numbers
  - Use hashing to provide temporary allele numbers / sequence types
- Has central database that can be accessed through an API by a corresponding web application and command-line tool

I would be happy to hear any feedback or insights on this. It looks like people may already be working on MLST based on the meeting notes, and I would like to get involved!

Thanks,
Sam

**Comment by iqbal-lab** [comment]
Hi there. Yes, many of us involved in this project are interested in different aspects of that idea.

1. For MLST alone - for salmonella there is a US initiative that sort of does this; also Enterobase does a lot; more broadly, I know pathogen.watch would like to do what you are suggesting.
2. You can already do something semi-related, which is to use a sourmash index to query to see which other genomes are like your index. There are indexes for all of SRA as of some-date.
3. My team has been interested in doing this for kmer-search or full alignment for several years - first just kmer search, then making it faster, and then last year using compression to enable full alignment.

But really truly making it real time and keepign up with public data is hard because the data doubles every couple of years - so it's much more about cost of provisioning hardware, and staffing than it is about anything technica/

**Comment by sam-baird** [comment]
Thank you for your insight and pointing to other resources and techniques that are looking to accomplish a similar goal. I will look  more into those.

Yes, it is challenging when it comes to provisioning resources and having a cost-effective solution for "real-time" updates. Some ideas I'm considering:

- Have AllTheBacteria as a baseline dataset once MLST is incorporated, then for any new samples found on INSDC that are not already in AllTheBacteria, have a daily workflow that would download the sequence data and perform MLST, selecting assemblies where available and raw reads as fallback.
- For the daily workflow, MLST would be performed on the raw data as it comes off INSDC, no assembly or QC would be performed, at least not initially.
- Run parallel jobs performing the downloading and typing (easier said than done).
- For typing raw reads, start with a partial download of the reads for the sample and attempt typing with stringMLST. If the initial typing attempt fails, download more reads. I have tested this a little bit and seemed to work well, but there could be an issue with selecting a non-random subsample of the reads due to sorting. I would need to test this more thoroughly.
- To keep the central MLST database lightweight, it would only store MLST results for each sample, IDs, taxon, and maybe some basic metadata but nothing else.

**Comment by iqbal-lab** [comment]
i think this is all interesting, but not an issue to be fixed as part of ATB. Closing
