### ISSUE TITLE
Missing species calls

### ISSUE THREAD

**Issue by snayfach** [AllTheBacteria/AllTheBacteria#51]
I may be missing something, but it seems that not all genomes are listed in the species-calls.tsv file. There are 2454637 records in the latest assemby-stats.tsv file `https://osf.io/download/nbyqv/` but only 2440377 in the species-calls.tsv file `https://osf.io/download/7t9qd/`. Both files are listed under `Aggregated/Latest_2024-08`. A few examples are SAMD00111213, SAMN28093670, and SAMEA7563967. Is this expected?

**Comment by martinghunt** [comment]
That is expected. The list of samples in release 0.2 + 202408 is this:

```
Aggregated/Latest_2024-08/sample_list.txt.gz	https://osf.io/download/ev3sj/
```

which lists the total of 2440377 samples in those two releases.

We process more samples, but they can fail for various reasons. This means some files, like assembly stats and the sylph files, contain a superset of the 2440377 samples. We've left them in there for completeness in case it's ever useful.

There's also the status file `status.202408.tsv.gz`, which has an overall answer to "what happened to this sample". It has "PASS" or "FAIL:..." in column 2. There's 2440377 in there that "PASS", which are the samples in the release, plus a bunch of fails:

```
$ zcat status.202408.tsv.gz  | cut -f2 | sort | uniq -c
  14260 FAIL:assembly_length_fail
      5 FAIL:downloaded_reads_fail
   5275 FAIL:shovill_fail
    288 FAIL:sylph_fail
    198 FAIL:timeout
2440377 PASS
      1 Status
```

Searching for your 3 samples listed above:

```
$ ls
all_atb_files.20241126.tsv  assembly-stats.tsv.gz  sample_list.txt.gz  species_calls.tsv.gz  status.202408.tsv.gz  sylph.no_matches.txt.gz

$ zgrep SAMD00111213 *.gz
assembly-stats.tsv.gz:SAMD00111213	75409	4	18852.25	62011	820	0	0	62011	1	62011	1	8267	2
status.202408.tsv.gz:SAMD00111213	FAIL:assembly_length_fail	reject	.

$ zgrep SAMN28093670 *.gz
assembly-stats.tsv.gz:SAMN28093670	5300102	146	36302.07	892287	227	0	0	217695	8	125864	14	55187	26
sample_list.txt.gz:SAMN28093670
species_calls.tsv.gz:SAMN28093670	Escherichia coli	T
status.202408.tsv.gz:SAMN28093670	PASS	r0.2	.

$ zgrep SAMEA7563967 *.gz
assembly-stats.tsv.gz:SAMEA7563967	4365480	131	33324.27	233885	211	0	0	105916	15	74857	24	40018	39
sample_list.txt.gz:SAMEA7563967
species_calls.tsv.gz:SAMEA7563967	Mycobacterium tuberculosis	T
status.202408.tsv.gz:SAMEA7563967	PASS	r0.2	.
```

SAMD00111213 was rejected because the assembly was too short. The other two samples look ok and do have species calls.
